name: bluespark
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2

  flutter_reactive_ble: ^5.0.2
  functional_data: ^1.0.0
  intl: ^0.17.0
  sliding_up_panel: ^2.0.0+1
  hexcolor: ^2.0.5
  carousel_slider: ^4.0.0
  horizontal_picker: ^1.2.0
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  dependency_validator: ^3.1.0
  functional_data_generator: ^1.1.2
  flutter_restart: ^0.0.3

  rounded_loading_button: ^2.0.8
  awesome_dialog: ^2.1.2
  loader_overlay: ^2.0.0-nullsafety.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  location: ^4.3.0
#  screen: ^0.0.5
  wakelock: ^0.6.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"






dependency_overrides:
  flutter_reactive_ble: ^5.0.2
  reactive_ble_mobile: ^5.0.2
  google_fonts: ^2.2.0


flutter:

  uses-material-design: true

  assets:
    - images/main_screen/
    - images/Montserrat/
    - images/Welcome/
    - images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: images/Montserrat/Montserrat-SemiBold.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/applogo.jpeg"